#!/bin/bash
# Generates HTML files in out directory from Latex files
set -e

BASE=$(pwd)
TEX4HT_CONFIG="$BASE/src/gen.cfg,xhtml,mathml,utf8"

files=(home hacking_openshift openshift containers testsuite)

function cleanup() {
  rm -rf _minted*
  rm $(ls -I "*.tex" -I "*.svg" -I "*.html" -I "*.css")
}

function build() {
  src_path=$BASE/src/$1
  src_file=$src_path/$1.tex

  cd $src_path
  pdflatex  -shell-escape -output-directory=$src_path/ $src_file
  htlatex $src_file "$TEX4HT_CONFIG" "" -d$src_path/ " -shell-escape"
  cleanup
  firefox $1.html &
}

trap 'cleanup' TERM INT EXIT

if [ "$1" == "all" ]; then
  for item in ${files[*]}
  do
    build $item
  done
else
  build $1
fi



